"""empty message

Revision ID: 35a1eb6e0d07
Revises: 
Create Date: 2018-07-18 12:06:05.397282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35a1eb6e0d07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Essays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('essays')
    op.add_column('user_user', sa.Column('user_id_followed', sa.Integer(), nullable=False))
    op.add_column('user_user', sa.Column('user_id_following', sa.Integer(), nullable=False))
    op.drop_constraint('user_user_ibfk_1', 'user_user', type_='foreignkey')
    op.create_foreign_key(None, 'user_user', 'user', ['user_id_followed'], ['id'])
    op.create_foreign_key(None, 'user_user', 'user', ['user_id_following'], ['id'])
    op.drop_column('user_user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_user', type_='foreignkey')
    op.drop_constraint(None, 'user_user', type_='foreignkey')
    op.create_foreign_key('user_user_ibfk_1', 'user_user', 'user', ['user_id'], ['id'])
    op.drop_column('user_user', 'user_id_following')
    op.drop_column('user_user', 'user_id_followed')
    op.create_table('essays',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='essays_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Essays')
    # ### end Alembic commands ###
